### ISSUE TITLE
Vertical Tabs component

### ISSUE THREAD

**Issue by aidengibbs** [GTBitsOfGood/bog-component-library#149]
### Issue Description
Make vertical tab component for use on our homepage website.

### Resources
https://www.figma.com/file/DEfDgRT4G9732YxrqTqq8V/OG-BoG-Design-System-(Working-File)?node-id=2949%3A17944[](url)![Screen Shot 2022-03-11 at 5.39.38 PM.png](https://images.zenhubusercontent.com/612eba4911d1aaff3f4e1ee0/c6e88c90-0886-4710-a25d-9e240e50fa84)

**Comment by lilyyang606** [comment]
https://www.figma.com/file/DEfDgRT4G9732YxrqTqq8V/OG-BoG-Design-System-(Working-File)?node-id=2949%3A17944
