### ISSUE TITLE
Button: Add Label Only to Tertiary Level

### ISSUE THREAD

**Issue by alysonlam** [GTBitsOfGood/bog-component-library#38]
An additional type of button, label only, has been added to the tertiary level.
![image.png](https://images.zenhubusercontent.com/61144bb180a7d08236aaf614/448c500b-3e98-4a78-9fbd-0430270f332f)

[Link to Figma](https://www.figma.com/file/DEfDgRT4G9732YxrqTqq8V/BoG-Component-Library-(Design-System)-%2F-Fall21?node-id=654%3A3799)

**Comment by therealsharath** [comment]
This feature has already been implemented by @jade-law. Closing this issue.
