### ISSUE TITLE
Alert Component

### ISSUE THREAD

**Issue by therealsharath** [GTBitsOfGood/bog-component-library#43]
### Issue Description
Follow the Figma mocks and create an alert story to support all the features defined on the linked Figma.

### Acceptance Criteria 
A customizable alert component that can be transformed into any form defined in the mocks.

### Customizable Parameters
- [ ] Background Color
- [ ] Type of alert (Success, Error, Message, Brand Message)
- [ ] Typography
- [ ] Border Stroke Weight
- [ ] Component Width
- [ ] Component Height (hug content vs. fixed)
- [ ] Margins (px)
- [ ] Horizontal Padding (px)
- [ ] Vertical Padding (px)
- [ ] Title Visibility (toggle)
- [ ] Icon Visibility (toggle)
- [ ] Close Visibility (toggle)
- [ ] Customizable Message
- [ ] Style Options (Filled, No fill)
- [ ] Customizable Button
- [ ] Customizable Type
- [ ] Corner Radius (px, default : 4 px)
- [ ] Custom Icon
- [ ] Icon Sizing (px)

### Figma Mocks
[Link](https://www.figma.com/file/DEfDgRT4G9732YxrqTqq8V/BoG-Component-Library-(Design-System)-%2F-Fall21?node-id=909%3A16607) to Figma.

![Alert.png](https://images.zenhubusercontent.com/60fe1174cc341fa054e58740/5064faa8-01b6-4ead-aed8-f793d86034e0)

**Comment by therealsharath** [comment]
@ematthews35 quick update on this ticket?

**Comment by ematthews35** [comment]
> @ematthews35 quick update on this ticket?

Sorry for the late response! Pushing my updated changes now, I believe I have most of the reqs complete, except: 
- the large alert with just the button
- the small alert with just text
- the small alert with text + button
- need to add the border prop to have the variations that have just an outline and no background color

**Comment by therealsharath** [comment]
Sounds good to me!
