### ISSUE TITLE
Tooltip component

### ISSUE THREAD

**Issue by therealsharath** [GTBitsOfGood/bog-component-library#44]
### Issue Description
Follow the Figma mocks and create a tooltip story to support all the features defined on the linked Figma.

### Acceptance Criteria 
A customizable tooltip that can be transformed into any defined in the mocks.

### Figma Mocks
[Link](https://www.figma.com/file/DEfDgRT4G9732YxrqTqq8V/BoG-Component-Library-(Design-System)-%2F-Fall21?node-id=913%3A12920) to Figma.

![Tooltip.png](https://images.zenhubusercontent.com/60fe1174cc341fa054e58740/e7ecfd85-8743-4652-a508-126eb1dd010e)

**Comment by alysonlam** [comment]
I will be adding another size for the tooltip so look out for that.
