### ISSUE TITLE
Gather content for the website

### ISSUE THREAD

**Issue by alysonlam** [GTBitsOfGood/bog-component-library#55]
Determine the content for the developer page and the design guideline page

**Comment by alysonlam** [comment]
@therealsharath send us the content you'd like for the website and what info we need to include. Slack is fine

**Comment by therealsharath** [comment]
Requirements for the website:
- Easy to navigate/use
- Gives clear instructions/guidelines about the design system
- Easy access to Figma & Storybook
- Preferably has video instructions on how to use the design system + library

**Comment by therealsharath** [comment]
Is this ticket done or do we still need to get more stuff for the copywriting/content of the website? @alysonlam @lilyyang606

**Comment by alysonlam** [comment]
we will have to continue with the copywriting since I’ve been kind of sick

**Comment by therealsharath** [comment]
👍

**Comment by lilyyang606** [comment]
I have been super busy these days. I just have the homepage ready... I will keep working on it. Here's the link:https://www.figma.com/file/DEfDgRT4G9732YxrqTqq8V/BoG-Design-System-(Working-File)?node-id=1389%3A11420
