### ISSUE TITLE
[SPIKE] Investigate testing components & setting up a testing library

### ISSUE THREAD

**Issue by therealsharath** [GTBitsOfGood/bog-component-library#86]
### Issue Description
Right now the components are only visually inspected by the EM & designers and do not have automated testing for checking functionality. We need to add an appropriate testing system to the component library to make sure our components are lightweight and reusable.

### Acceptance Criteria 
- [ ] A testing library
- [ ] Writeup on how to use/setup tests

### User Story 
Our components are not tested :(

**Comment by Fattimo** [comment]
https://www.denniskortsch.de/posts/component-library-storybook
https://storybook.js.org/docs/react/writing-tests/interaction-testing (storybook also has stuff like accessibility and other testing)

**Comment by therealsharath** [comment]
https://storybook.js.org/tutorials/ui-testing-handbook/

**Comment by Fattimo** [comment]
directory structure: https://github.com/chakra-ui/chakra-ui/tree/main/packages/input
